### ISSUE TITLE
[as2_python_api] The use of drone_id in MissionUpdate msg

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#328]
### Feature Description

The MissionUpdate has a field drone_id:
https://github.com/aerostack2/aerostack2/blob/7b68754dd0c8ea2e1d291621c449d53dd4656a2d/as2_msgs/msg/MissionUpdate.msg#L3 
Which is the use of it?

If the MissionUpdate is use by the MissionExecutor (ros2_adapter + mission_interpreter + drone_interface), which only has one drone_interface, by is drone_id necessary?

- If there are a unique topic /mission_update, each MissionExecutor must evaluate drone_id field to check if it match with its drone_interface. But, we are currently using drone_id as a String in out drone_interface, so I think the best option is to use string for this field.

- If there are multiples topics using namespace, such as /namespace/mission_update, there is no need to add drone_id field.

## MissionUpdate.msg 
> int32 drone_id
> int32 mission_id
> int32 item_id
> 
> uint8 EXECUTE = 0
> uint8 LOAD    = 1
> uint8 START   = 2
> uint8 PAUSE   = 3
> uint8 RESUME  = 4
> uint8 STOP    = 5
> uint8 JUMP_TO = 6
> uint8 REPEAT  = 7
> uint8 INSERT  = 8
> uint8 MODIFY  = 9
> uint8 REMOVE  = 10
> uint8 RESET   = 11
> uint8 ABORT   = 12
> 
> uint8 type
> 
> string mission

**Comment by pariaspe** [comment]
Hey @RPS98, as I see it:
1. Whether we use one or several `/mission_updates` topics depend on the architecture used. Since the architecture used is not clear right now, I would suggest to keep it even if the parameter is not used.
2. I asked myself the same question while coding that. I would use an `integer`, but since we are identifying each drone by its namespace I came with a mixed solution that smells pretty bad (see code snippet below, whether deal with a new update or not). I believe it makes more sense to use an integer as ID, but then how to link them with each drone?
https://github.com/aerostack2/aerostack2/blob/7b68754dd0c8ea2e1d291621c449d53dd4656a2d/as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py#L92-L94
