### ISSUE TITLE
[as2_motion_reference_handlers] New constructor methods giving namespace

### ISSUE THREAD

**Issue by pariaspe** [aerostack2/aerostack2#329]
Current class constructor only accepts one argument: a raw pointer to a `as2::Node`. This implies that you can only use these handlers if the node created shares the namespace with the drone (see code snippet below), otherwise topics do not match. I believe that it shouldn't be mandatory to use the same namespace.
Besides, why not to also accept standard `rclcpp::Node`?  

https://github.com/aerostack2/aerostack2/blob/7b68754dd0c8ea2e1d291621c449d53dd4656a2d/as2_motion_reference_handlers/src/basic_motion_references.cpp#L38-L51

**Comment by RPS98** [comment]
From what I understand, you want a single node to have different `as2::motionReferenceHandlers` so that you can control different drones from the same node. I understand that the solution is to pass an optional argument with the desired namespace, and by default, it should use the node's namespace. 

Nevertheless, I believe that Aerostack2's philosophy is to use behaviors, and these can indeed be called from the same node to control different drones.
