### ISSUE TITLE
[as2_msgs] In GoToWaypoint.action target_pose is of type PointStamped

### ISSUE THREAD

**Issue by tompe17** [aerostack2/aerostack2#371]
### ROS2 Version

humble

### Version

main

### What happened?

In GoToWaypoint.action target_pose is of type PointStamped.  The documentation for YawMode refer to flying with "Yaw angle is set by pose orientation".

To me this is inconsistent and confusing.  Ought to be a bug.

**Comment by RPS98** [comment]
Hi @tompe17,

Currently, the `GoToWaypoint` behavior, that uses the `GoToWaypoint.action`, does not support the `YAW_FROM_ORIENTATION` yaw mode. 

Currently supported control modes are:
- `PATH_FACING`
- `FIXED_YAW`
- `KEEP_YAW`. 

In `FIXED_YAW`, the user sets the desired yaw angle using the field `angle` of the `YawMode.msg` message.

Others components in Aerostack2 use `YAW_FROM_ORIENTATION` from the `YawMode.msg`, that's why it exists. We must update the documentation to list the available yaw modes for each behavior.
